news_sites:
  elmundo:
    url: https://www.elmundo.es/
    queries:
      homepage_article_links: '.ue-c-cover-content__link'
      article_body: '.ue-c-article__body'
      article_title: '.ue-c-article__headline'
  theguardian:
    url: https://www.theguardian.com/international
    queries:
      homepage_article_links: '.u-faux-block-link__overlay '
      article_body: '.content__article-body'
      article_title: '.content__headline'